import { Federant, Mozilla_Headline } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const federant = Federant({
  subsets: ["latin"],
  variable: "--font-federant",
  weight: "400",
  display: "swap",
});

const mozillaHeadline = Mozilla_Headline({
  subsets: ["latin"],
  variable: "--font-mozillaHeadline",
  weight: ["400", "700"],
  display: "swap",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${federant.variable} ${mozillaHeadline.variable}`}
      >
        <Navbar/>
        <main className="min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
